import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { bentonSans } from "@/lib/fonts";
import { Providers } from "@/providers/RootProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={bentonSans.className}>
      <body className="antialiased" >
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
